///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModel {
/*
{
  "secureKey": 213
} 
*/

  int? secureKey;

  LoginModel({
    this.secureKey,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    secureKey = json['secureKey']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['secureKey'] = secureKey;
    return data;
  }
}
